[package]
name = "core"
description = "DESCRIPTION"
documentation = "DOCUMENTATION"
readme = "README"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true


[[bin]]
name = "fast_forward"
path = "src/main.rs"

[features]
default = ["full"]
full = []

[dependencies]
log.workspace = true
colour.workspace = true
log4rs = "*"
shared.workspace = true

burn = { version = "0.16.0", features = ["wgpu", "train", "accelerate", "candle", "fusion"] }
bincode = "=2.0.0-rc.3"
bincode_derive = "=2.0.0-rc.3"

# burn.workspace = true
serde.workspace = true

rayon = "*"
ndarray = "*"
rand = "0.9"
rand_distr = "0.5"

# [dependencies.bincode]
# git = "https://github.com/bincode-org/bincode.git"
# tag = "v2.0.0-rc.3"
#
# [dependencies.bincode_derive]
# git = "https://github.com/bincode-org/bincode.git"
# tag = "v2.0.0-rc.3"
#
# [patch.crates-io.bincode]
# git = "https://github.com/bincode-org/bincode.git"
# tag = "v2.0.0-rc.3"
#
# [patch.crates-io.bincode_derive]
# git = "https://github.com/bincode-org/bincode.git"
# tag = "v2.0.0-rc.3"

# [ init code ]

# [ macro ]

#[macro_use] extern crate log;




[build-dependencies]
build_cfg.workspace = true
rustc_version.workspace = true

#[package.metadata.docs.rs]
#targets = ["x86_64-unknown-linux-gnu"]

